### ISSUE TITLE
Tensorflow in Windows

### ISSUE THREAD

**Issue by HosnaCSE** [fabianbormann/Tensorflow_Segmentation#10]
Can I compile and execute this code on windows? I tried like 

"pip install -r requirement.txt
Then get error:
Could not open requirements file: [Errno 2] No such file or directory: 'requirement.txt'"

I think I may not using right command. I am very beginner at this.......:(

**Comment by fastlater** [comment]
Your error message means you dont have the txt file, that is all. But that txt only mention that you need to have installed the wget and numpy.

**Comment by fastlater** [comment]
I realized that your message is from Dec, 2016. I guess you solved your problem long time ago.

**Comment by HosnaCSE** [comment]
Hello,
Yeah, I did solve the error, indeed. Thanks for your concern, I appreciate it. 
Thanks
Hosna
