### ISSUE TITLE
Trained weights?

### ISSUE THREAD

**Issue by kukuruza** [fabianbormann/Tensorflow_Segmentation#11]
Hello! Is the trained network weights available for download somewhere?

**Comment by fabianbormann** [comment]
Hi @kukuruza, we are going to provide trained weights asap.

**Comment by TheShadow29** [comment]
@fabianbormann is there any updates as to where the trained weights can be found?

**Comment by stridom** [comment]
Hi, where can i find the well trained weights ?

**Comment by fabianbormann** [comment]
I'm working on it.. please check #27 for updates
