### ISSUE TITLE
Error in DeconvNet.py

### ISSUE THREAD

**Issue by hungnguyen0606** [fabianbormann/Tensorflow_Segmentation#16]
There are some errors I've found recently when trying to reproduce the result.

1) restore_session -> doesn't have 'self' as param
2) in predict: feed_dict={image:[image]} -> {self.x:[image]}

**Comment by codesteller86** [comment]
I am facing same issue. Is there any update on this issue?

**Comment by hungnguyen0606** [comment]
I think you can fix it as I mentioned above.

**Comment by codesteller86** [comment]
@hungnguyen0606 yup it worked thanks.
