### ISSUE TITLE
Deconv_1_1

### ISSUE THREAD

**Issue by hamidrezafazlali** [fabianbormann/Tensorflow_Segmentation#26]
Hello,
I read the original paper and there was no deconv layer with 32 filters, but in the code I saw this:

deconv_1_1 = self.deconv_layer(deconv_1_2, [3, 3, 32, 64], 32, 'deconv_1_1')

I really appreciate if someone helps me with that.

**Comment by RaydonLiu** [comment]
I samely have this question, I think maybe have a mistake in typing.
In my opinion, this should be:
    deconv_1_1 = self.deconv_layer(deconv_1_2, [3, 3, 3, 64], 3, 'deconv_1_1')
    score_1 = self.deconv_layer(deconv_1_1, [1, 1, 21, 3], 21, 'score_1')
The last, the output in 4D Tensor [batch_size ,image_width, image_height, class_num], this is class_num is the number of object  categories., i.e. class_num=21(including background).
I really appreciate to correct me if I have a misunderstanding.

**Comment by fabianbormann** [comment]
closed by e4d59e9
